versión: "3.9"

services: 
  NomMiApp:
    build:   
      context: .
      dockerfile: Dockerfile.dev 
    ports:
       - "3000:3000"     
    links:
       - mongoF
    volumes:
       - .:/home/app

  mongo01: 
     image: mongo
     ports:
        - "27017:27017" 
     environment:

      volumes:
         - mongo-data: /data/db      

  postgres01: 
     image: postgres
     ports:
        - "27017:27017" 
     environment:

      volumes:
        - postgres -> /var/lib/PostgreSQL/data
  


  python01: 
     image: python
     ports:
        - "27017:27017" 
     environment:

      volumes:
         - mongo-data: /data/db    


  node01: 
     image: node
     ports:
        - "3000:3000" 
     environment:


version: '3.8'  
services:  
  db:  
    container_name: pg_container  
    image: postgres  
    restart: always  
    environment:  
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root  
      POSTGRES_DB: name_db  
    ports:  
      - "5432:5432"  
  pgadmin:  
    container_name: pgadmin4_container  
    image: dpage/pgadmin4  
    restart: always  
    environment:  
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com  
      PGADMIN_DEFAULT_PASSWORD: root  
    ports:  
      - "5050:80"

      "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.22.0.3",


volumes:
   mongo-data: